---
book_repo: pivotal-cf/docs-book-wiki
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: master

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

elastic_search: true

public_host: docs-wiki.cfapps.io

products:
  - id: pcf
    subnav_root: wiki/index.html

sections:
- repository:
    name: pivotal-cf-experimental/docs-wiki-internal
  directory: wiki
  product_id: pcf
  product_info:
    use_local_header: true
    latest_stable_version: 1.0
    local_header_img: /images/cloud_rings.png
    local_header_title: Docs Wiki
    search_placeholder: Search Docs Wiki
    url_prefix: wiki
    local_product_version:
    local_header_links: []
    local_header_version_list:

template_variables:
  use_global_header: true
  book_title: Pivotal Docs Wiki
  book_title_short: Docs Wiki
  title: <span class="title-deemph">Pivotal</span> Docs Wiki
  title_image: images/icon-p-green.jpg
  hero_text: "Detailed documentation for Pivotal documentarians."

